version: "3"
services:
      Angular_app:
            container_name: angularApp
            restart: always
            build: .
            ports: 
                - ""
            links:
              - MongoDB
      MongoDB:
            container_name: myDB
            image: "mongo:latest"
            volumes:
                - ./mongo-volume:/data/db
            ports:
                - "27017:27017"            
