version: "3"
services:
      angular_app:
            container_name: angularApp
            restart: always
            build: .
            ports: 
                - "8081:8081"
            links:
              - mongoDB
      mongoDB:
            container_name: myDB
            image: "mongo:latest"
            volumes:
                - ./mongo-volume:/data/db
            ports:
                - "27017:27017"            
